application: yasta
version: 2
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /twiml
  static_dir: _twiml
  
- url: /.*
  script: yasta.app

  
libraries:
- name: webapp2
  version: latest
  
- name: jinja2
  version: latest
